### ISSUE TITLE
The Linux preset requires additional filters to reject junky CC and LD build commands 

### ISSUE THREAD

**Issue by IljaZakharov** [17451k/clade#30]
Experimenting with the linux bases I noted that load_all_cmds_by_type provides more commands than expected by the implied preset. In PDF file I do not observe these commands but the method returns them.

For instance, there are commands with empty in files attribute or .tmp\w+.s in files.

**Comment by 17451k** [comment]
CC extension simply do not save filtered commands to disk, so load_all_cmds_by_type() method can't return them. They are deleted and no longer exist.

However, there are no filters to delete commands without input files, or with assembler files. So, to fix the issue you just need to add them to the preset.

PDF file is not an accurate representation of the command graph since it shows connection between files, not commands.

**Comment by IljaZakharov** [comment]
Agree, you are right. The reason is that on my system for linux 2.6.33 I need to add additional filters to preset.
