### ISSUE TITLE
SrcGraph.as_picture does not work

### ISSUE THREAD

**Issue by eunovm** [17451k/clade#51]
There is such the option in the preset configuration, but it seems to have no effect.

**Comment by 17451k** [comment]
I have removed this option since currently there is no ability to print src graph using Graphviz. Moreover, it is not clear how to print it in a graph form, so this option probably will not be needed in the future.

By the way, I have added an alternative representation of cmd graph that you may find useful in 3d03797be22ffca474f552221a8c13df7f514dd5.
