### ISSUE TITLE
Add ability to specify which information to obtain with the Info extension

### ISSUE THREAD

**Issue by 17451k** [17451k/clade#93]
Sometimes some information, like about global variables initializations, is simply not needed, but its obtaining requires additional time and may even cause CIF to fail on some commands. It would be nice to be able to explicitly specify which information to collect.

I think that implementation of this request will require to split info.aspect file into several smaller aspect files, which can be included into info.aspect if the corresponding option is set.

**Comment by eunovm** [comment]
> Sometimes some information, like about global variables initializations, is simply not needed, but its obtaining requires additional time and may even cause CIF to fail on some commands. It would be nice to be able to explicitly specify which information to collect.
 
Unfortunately, in many cases you will not overcome CIF failures since it collects information on join points in advance. Later most of this information, especially with your adjustments, will not be necessary.

> I think that implementation of this request will require to split info.aspect file into several smaller aspect files, which can be included into info.aspect if the corresponding option is set.

I suggest that it is more naturally to use [conditional preprocessing](https://gcc.gnu.org/onlinedocs/cpp/Conditionals.html#Conditionals).
